# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8ddaa23484ca20c26bd59bdbce2a3db4d96cfb1b1c7d83130f3870afb7a45768a0330d5503356c253b12244f14dad7fccd073d711c100d3fa5caf18448ab89

test:
  secret_key_base: a0cebe6f5ccdf008787d4a612050eccdafac9f2bdb59a359616b3fedda56e9b23256429453c181d291e59cf1de3e5b5b70c6efe1ee6b294d2fe71112afc00bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
